version: '3'

services:   
  load_test:
    build: ./load_test
    command: python -m load_test.functions.run_it
    environment:
      - GITHUB_PROTOCOL=https
      - GITHUB_HOSTNAME=ghe-dev.sphereci.com
      - GITHUB_USER_OR_ORG_NAME=testgeorge
      - GITHUB_TOKEN=<your_token>
      - NUMBER_OF_REPOS=5
      - FILENAME=try-num-times.txt
    logging:
      driver: json-file
    volumes:
      - ./load_test:/code
