version: '3'

services:   
  load_test:
    build: ./load_test
    command: python -m load_test.functions.run_it
    environment:
      - GITHUB_PROTOCOL=https
      - GITHUB_HOSTNAME=<github.com>
      - GITHUB_USER_OR_ORG_NAME=
      - GITHUB_USERNAME=
      - GITHUB_TOKEN=
      - NUMBER_OF_REPOS=1
      - FILENAME=try-num-times.txt
    logging:
      driver: json-file
    volumes:
      - ./load_test:/code
