version: '3'

services:   
  load_test:
    build: ./load_test
    command: python -m load_test.functions.run_it
    environment:
      - GITHUB_USER_NAME=testgeorge
      - TOKEN=  
      - GITHUB_URI=https://ghe-dev.sphereci.com/
      - NUMBER_OF_REPOS=1
      - FILENAME=try-num-times.txt
    logging:
      driver: json-file
    volumes:
      - ./load_test:/code
